---
Name: dev-build-benchmark
After: databaseconnectors
---
SilverStripe\Core\Injector\Injector:
  MySQLDatabase:
    class: zzz\emteknetnz\DevBuildBenchmark\DevBuildBenchmarkMySQLDatabase

SilverStripe\ORM\DatabaseAdmin:
  extensions:
    - zzz\emteknetnz\DevBuildBenchmark\DatabaseAdminExtension
